#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SachOnline.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SachOnline")]
	public partial class dbSachOnlineDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadmin(admin instance);
    partial void Updateadmin(admin instance);
    partial void Deleteadmin(admin instance);
    partial void Insertchi_tiet_dat_hang(chi_tiet_dat_hang instance);
    partial void Updatechi_tiet_dat_hang(chi_tiet_dat_hang instance);
    partial void Deletechi_tiet_dat_hang(chi_tiet_dat_hang instance);
    partial void Insertchu_de(chu_de instance);
    partial void Updatechu_de(chu_de instance);
    partial void Deletechu_de(chu_de instance);
    partial void Insertdon_dat_hang(don_dat_hang instance);
    partial void Updatedon_dat_hang(don_dat_hang instance);
    partial void Deletedon_dat_hang(don_dat_hang instance);
    partial void Insertkhach_hang(khach_hang instance);
    partial void Updatekhach_hang(khach_hang instance);
    partial void Deletekhach_hang(khach_hang instance);
    partial void Insertnha_xuat_ban(nha_xuat_ban instance);
    partial void Updatenha_xuat_ban(nha_xuat_ban instance);
    partial void Deletenha_xuat_ban(nha_xuat_ban instance);
    partial void Insertsach(sach instance);
    partial void Updatesach(sach instance);
    partial void Deletesach(sach instance);
    partial void Inserttac_gia(tac_gia instance);
    partial void Updatetac_gia(tac_gia instance);
    partial void Deletetac_gia(tac_gia instance);
    partial void Insertviet_sach(viet_sach instance);
    partial void Updateviet_sach(viet_sach instance);
    partial void Deleteviet_sach(viet_sach instance);
    #endregion
		
		public dbSachOnlineDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbSachOnlineDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbSachOnlineDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbSachOnlineDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<admin> admins
		{
			get
			{
				return this.GetTable<admin>();
			}
		}
		
		public System.Data.Linq.Table<chi_tiet_dat_hang> chi_tiet_dat_hangs
		{
			get
			{
				return this.GetTable<chi_tiet_dat_hang>();
			}
		}
		
		public System.Data.Linq.Table<chu_de> chu_des
		{
			get
			{
				return this.GetTable<chu_de>();
			}
		}
		
		public System.Data.Linq.Table<don_dat_hang> don_dat_hangs
		{
			get
			{
				return this.GetTable<don_dat_hang>();
			}
		}
		
		public System.Data.Linq.Table<khach_hang> khach_hangs
		{
			get
			{
				return this.GetTable<khach_hang>();
			}
		}
		
		public System.Data.Linq.Table<nha_xuat_ban> nha_xuat_bans
		{
			get
			{
				return this.GetTable<nha_xuat_ban>();
			}
		}
		
		public System.Data.Linq.Table<sach> saches
		{
			get
			{
				return this.GetTable<sach>();
			}
		}
		
		public System.Data.Linq.Table<tac_gia> tac_gias
		{
			get
			{
				return this.GetTable<tac_gia>();
			}
		}
		
		public System.Data.Linq.Table<viet_sach> viet_saches
		{
			get
			{
				return this.GetTable<viet_sach>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin")]
	public partial class admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _admin_id;
		
		private string _username;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onadmin_idChanging(int value);
    partial void Onadmin_idChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int admin_id
		{
			get
			{
				return this._admin_id;
			}
			set
			{
				if ((this._admin_id != value))
				{
					this.Onadmin_idChanging(value);
					this.SendPropertyChanging();
					this._admin_id = value;
					this.SendPropertyChanged("admin_id");
					this.Onadmin_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chi_tiet_dat_hang")]
	public partial class chi_tiet_dat_hang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _chi_tiet_id;
		
		private System.Nullable<int> _don_dat_hang_id;
		
		private System.Nullable<int> _sach_id;
		
		private System.Nullable<int> _so_luong;
		
		private EntityRef<don_dat_hang> _don_dat_hang;
		
		private EntityRef<sach> _sach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onchi_tiet_idChanging(int value);
    partial void Onchi_tiet_idChanged();
    partial void Ondon_dat_hang_idChanging(System.Nullable<int> value);
    partial void Ondon_dat_hang_idChanged();
    partial void Onsach_idChanging(System.Nullable<int> value);
    partial void Onsach_idChanged();
    partial void Onso_luongChanging(System.Nullable<int> value);
    partial void Onso_luongChanged();
    #endregion
		
		public chi_tiet_dat_hang()
		{
			this._don_dat_hang = default(EntityRef<don_dat_hang>);
			this._sach = default(EntityRef<sach>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chi_tiet_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int chi_tiet_id
		{
			get
			{
				return this._chi_tiet_id;
			}
			set
			{
				if ((this._chi_tiet_id != value))
				{
					this.Onchi_tiet_idChanging(value);
					this.SendPropertyChanging();
					this._chi_tiet_id = value;
					this.SendPropertyChanged("chi_tiet_id");
					this.Onchi_tiet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_don_dat_hang_id", DbType="Int")]
		public System.Nullable<int> don_dat_hang_id
		{
			get
			{
				return this._don_dat_hang_id;
			}
			set
			{
				if ((this._don_dat_hang_id != value))
				{
					if (this._don_dat_hang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondon_dat_hang_idChanging(value);
					this.SendPropertyChanging();
					this._don_dat_hang_id = value;
					this.SendPropertyChanged("don_dat_hang_id");
					this.Ondon_dat_hang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sach_id", DbType="Int")]
		public System.Nullable<int> sach_id
		{
			get
			{
				return this._sach_id;
			}
			set
			{
				if ((this._sach_id != value))
				{
					if (this._sach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsach_idChanging(value);
					this.SendPropertyChanging();
					this._sach_id = value;
					this.SendPropertyChanged("sach_id");
					this.Onsach_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int")]
		public System.Nullable<int> so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="don_dat_hang_chi_tiet_dat_hang", Storage="_don_dat_hang", ThisKey="don_dat_hang_id", OtherKey="don_dat_hang_id", IsForeignKey=true)]
		public don_dat_hang don_dat_hang
		{
			get
			{
				return this._don_dat_hang.Entity;
			}
			set
			{
				don_dat_hang previousValue = this._don_dat_hang.Entity;
				if (((previousValue != value) 
							|| (this._don_dat_hang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._don_dat_hang.Entity = null;
						previousValue.chi_tiet_dat_hangs.Remove(this);
					}
					this._don_dat_hang.Entity = value;
					if ((value != null))
					{
						value.chi_tiet_dat_hangs.Add(this);
						this._don_dat_hang_id = value.don_dat_hang_id;
					}
					else
					{
						this._don_dat_hang_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("don_dat_hang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sach_chi_tiet_dat_hang", Storage="_sach", ThisKey="sach_id", OtherKey="sach_id", IsForeignKey=true)]
		public sach sach
		{
			get
			{
				return this._sach.Entity;
			}
			set
			{
				sach previousValue = this._sach.Entity;
				if (((previousValue != value) 
							|| (this._sach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sach.Entity = null;
						previousValue.chi_tiet_dat_hangs.Remove(this);
					}
					this._sach.Entity = value;
					if ((value != null))
					{
						value.chi_tiet_dat_hangs.Add(this);
						this._sach_id = value.sach_id;
					}
					else
					{
						this._sach_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("sach");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chu_de")]
	public partial class chu_de : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _chu_de_id;
		
		private string _ten_chu_de;
		
		private EntitySet<sach> _saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onchu_de_idChanging(int value);
    partial void Onchu_de_idChanged();
    partial void Onten_chu_deChanging(string value);
    partial void Onten_chu_deChanged();
    #endregion
		
		public chu_de()
		{
			this._saches = new EntitySet<sach>(new Action<sach>(this.attach_saches), new Action<sach>(this.detach_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chu_de_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int chu_de_id
		{
			get
			{
				return this._chu_de_id;
			}
			set
			{
				if ((this._chu_de_id != value))
				{
					this.Onchu_de_idChanging(value);
					this.SendPropertyChanging();
					this._chu_de_id = value;
					this.SendPropertyChanged("chu_de_id");
					this.Onchu_de_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_chu_de", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten_chu_de
		{
			get
			{
				return this._ten_chu_de;
			}
			set
			{
				if ((this._ten_chu_de != value))
				{
					this.Onten_chu_deChanging(value);
					this.SendPropertyChanging();
					this._ten_chu_de = value;
					this.SendPropertyChanged("ten_chu_de");
					this.Onten_chu_deChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chu_de_sach", Storage="_saches", ThisKey="chu_de_id", OtherKey="chu_de_id")]
		public EntitySet<sach> saches
		{
			get
			{
				return this._saches;
			}
			set
			{
				this._saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.chu_de = this;
		}
		
		private void detach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.chu_de = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.don_dat_hang")]
	public partial class don_dat_hang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _don_dat_hang_id;
		
		private System.Nullable<int> _khach_hang_id;
		
		private System.Nullable<System.DateTime> _ngay_dat;
		
		private EntitySet<chi_tiet_dat_hang> _chi_tiet_dat_hangs;
		
		private EntityRef<khach_hang> _khach_hang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondon_dat_hang_idChanging(int value);
    partial void Ondon_dat_hang_idChanged();
    partial void Onkhach_hang_idChanging(System.Nullable<int> value);
    partial void Onkhach_hang_idChanged();
    partial void Onngay_datChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_datChanged();
    #endregion
		
		public don_dat_hang()
		{
			this._chi_tiet_dat_hangs = new EntitySet<chi_tiet_dat_hang>(new Action<chi_tiet_dat_hang>(this.attach_chi_tiet_dat_hangs), new Action<chi_tiet_dat_hang>(this.detach_chi_tiet_dat_hangs));
			this._khach_hang = default(EntityRef<khach_hang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_don_dat_hang_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int don_dat_hang_id
		{
			get
			{
				return this._don_dat_hang_id;
			}
			set
			{
				if ((this._don_dat_hang_id != value))
				{
					this.Ondon_dat_hang_idChanging(value);
					this.SendPropertyChanging();
					this._don_dat_hang_id = value;
					this.SendPropertyChanged("don_dat_hang_id");
					this.Ondon_dat_hang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khach_hang_id", DbType="Int")]
		public System.Nullable<int> khach_hang_id
		{
			get
			{
				return this._khach_hang_id;
			}
			set
			{
				if ((this._khach_hang_id != value))
				{
					if (this._khach_hang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkhach_hang_idChanging(value);
					this.SendPropertyChanging();
					this._khach_hang_id = value;
					this.SendPropertyChanged("khach_hang_id");
					this.Onkhach_hang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_dat", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_dat
		{
			get
			{
				return this._ngay_dat;
			}
			set
			{
				if ((this._ngay_dat != value))
				{
					this.Onngay_datChanging(value);
					this.SendPropertyChanging();
					this._ngay_dat = value;
					this.SendPropertyChanged("ngay_dat");
					this.Onngay_datChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="don_dat_hang_chi_tiet_dat_hang", Storage="_chi_tiet_dat_hangs", ThisKey="don_dat_hang_id", OtherKey="don_dat_hang_id")]
		public EntitySet<chi_tiet_dat_hang> chi_tiet_dat_hangs
		{
			get
			{
				return this._chi_tiet_dat_hangs;
			}
			set
			{
				this._chi_tiet_dat_hangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khach_hang_don_dat_hang", Storage="_khach_hang", ThisKey="khach_hang_id", OtherKey="khach_hang_id", IsForeignKey=true)]
		public khach_hang khach_hang
		{
			get
			{
				return this._khach_hang.Entity;
			}
			set
			{
				khach_hang previousValue = this._khach_hang.Entity;
				if (((previousValue != value) 
							|| (this._khach_hang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khach_hang.Entity = null;
						previousValue.don_dat_hangs.Remove(this);
					}
					this._khach_hang.Entity = value;
					if ((value != null))
					{
						value.don_dat_hangs.Add(this);
						this._khach_hang_id = value.khach_hang_id;
					}
					else
					{
						this._khach_hang_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("khach_hang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chi_tiet_dat_hangs(chi_tiet_dat_hang entity)
		{
			this.SendPropertyChanging();
			entity.don_dat_hang = this;
		}
		
		private void detach_chi_tiet_dat_hangs(chi_tiet_dat_hang entity)
		{
			this.SendPropertyChanging();
			entity.don_dat_hang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khach_hang")]
	public partial class khach_hang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _khach_hang_id;
		
		private string _ten_khach_hang;
		
		private string _dia_chi;
		
		private string _email;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _DienThoai;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private EntitySet<don_dat_hang> _don_dat_hangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkhach_hang_idChanging(int value);
    partial void Onkhach_hang_idChanged();
    partial void Onten_khach_hangChanging(string value);
    partial void Onten_khach_hangChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    #endregion
		
		public khach_hang()
		{
			this._don_dat_hangs = new EntitySet<don_dat_hang>(new Action<don_dat_hang>(this.attach_don_dat_hangs), new Action<don_dat_hang>(this.detach_don_dat_hangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khach_hang_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int khach_hang_id
		{
			get
			{
				return this._khach_hang_id;
			}
			set
			{
				if ((this._khach_hang_id != value))
				{
					this.Onkhach_hang_idChanging(value);
					this.SendPropertyChanging();
					this._khach_hang_id = value;
					this.SendPropertyChanged("khach_hang_id");
					this.Onkhach_hang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_khach_hang", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ten_khach_hang
		{
			get
			{
				return this._ten_khach_hang;
			}
			set
			{
				if ((this._ten_khach_hang != value))
				{
					this.Onten_khach_hangChanging(value);
					this.SendPropertyChanging();
					this._ten_khach_hang = value;
					this.SendPropertyChanged("ten_khach_hang");
					this.Onten_khach_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(15)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(15)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(10)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khach_hang_don_dat_hang", Storage="_don_dat_hangs", ThisKey="khach_hang_id", OtherKey="khach_hang_id")]
		public EntitySet<don_dat_hang> don_dat_hangs
		{
			get
			{
				return this._don_dat_hangs;
			}
			set
			{
				this._don_dat_hangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_don_dat_hangs(don_dat_hang entity)
		{
			this.SendPropertyChanging();
			entity.khach_hang = this;
		}
		
		private void detach_don_dat_hangs(don_dat_hang entity)
		{
			this.SendPropertyChanging();
			entity.khach_hang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nha_xuat_ban")]
	public partial class nha_xuat_ban : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nha_xuat_ban_id;
		
		private string _ten_nha_xuat_ban;
		
		private string _dia_chi;
		
		private EntitySet<sach> _saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnha_xuat_ban_idChanging(int value);
    partial void Onnha_xuat_ban_idChanged();
    partial void Onten_nha_xuat_banChanging(string value);
    partial void Onten_nha_xuat_banChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    #endregion
		
		public nha_xuat_ban()
		{
			this._saches = new EntitySet<sach>(new Action<sach>(this.attach_saches), new Action<sach>(this.detach_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nha_xuat_ban_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nha_xuat_ban_id
		{
			get
			{
				return this._nha_xuat_ban_id;
			}
			set
			{
				if ((this._nha_xuat_ban_id != value))
				{
					this.Onnha_xuat_ban_idChanging(value);
					this.SendPropertyChanging();
					this._nha_xuat_ban_id = value;
					this.SendPropertyChanged("nha_xuat_ban_id");
					this.Onnha_xuat_ban_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_nha_xuat_ban", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten_nha_xuat_ban
		{
			get
			{
				return this._ten_nha_xuat_ban;
			}
			set
			{
				if ((this._ten_nha_xuat_ban != value))
				{
					this.Onten_nha_xuat_banChanging(value);
					this.SendPropertyChanging();
					this._ten_nha_xuat_ban = value;
					this.SendPropertyChanged("ten_nha_xuat_ban");
					this.Onten_nha_xuat_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nha_xuat_ban_sach", Storage="_saches", ThisKey="nha_xuat_ban_id", OtherKey="nha_xuat_ban_id")]
		public EntitySet<sach> saches
		{
			get
			{
				return this._saches;
			}
			set
			{
				this._saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.nha_xuat_ban = this;
		}
		
		private void detach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.nha_xuat_ban = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sach")]
	public partial class sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sach_id;
		
		private string _ten_sach;
		
		private System.Nullable<int> _tac_gia_id;
		
		private System.Nullable<int> _nha_xuat_ban_id;
		
		private decimal _gia_tien;
		
		private System.Nullable<int> _chu_de_id;
		
		private string _anhSP;
		
		private System.Nullable<System.DateTime> _NgayCapNhap;
		
		private string _mo_ta;
		
		private EntitySet<chi_tiet_dat_hang> _chi_tiet_dat_hangs;
		
		private EntitySet<viet_sach> _viet_saches;
		
		private EntityRef<nha_xuat_ban> _nha_xuat_ban;
		
		private EntityRef<chu_de> _chu_de;
		
		private EntityRef<tac_gia> _tac_gia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsach_idChanging(int value);
    partial void Onsach_idChanged();
    partial void Onten_sachChanging(string value);
    partial void Onten_sachChanged();
    partial void Ontac_gia_idChanging(System.Nullable<int> value);
    partial void Ontac_gia_idChanged();
    partial void Onnha_xuat_ban_idChanging(System.Nullable<int> value);
    partial void Onnha_xuat_ban_idChanged();
    partial void Ongia_tienChanging(decimal value);
    partial void Ongia_tienChanged();
    partial void Onchu_de_idChanging(System.Nullable<int> value);
    partial void Onchu_de_idChanged();
    partial void OnanhSPChanging(string value);
    partial void OnanhSPChanged();
    partial void OnNgayCapNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhapChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    #endregion
		
		public sach()
		{
			this._chi_tiet_dat_hangs = new EntitySet<chi_tiet_dat_hang>(new Action<chi_tiet_dat_hang>(this.attach_chi_tiet_dat_hangs), new Action<chi_tiet_dat_hang>(this.detach_chi_tiet_dat_hangs));
			this._viet_saches = new EntitySet<viet_sach>(new Action<viet_sach>(this.attach_viet_saches), new Action<viet_sach>(this.detach_viet_saches));
			this._nha_xuat_ban = default(EntityRef<nha_xuat_ban>);
			this._chu_de = default(EntityRef<chu_de>);
			this._tac_gia = default(EntityRef<tac_gia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sach_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sach_id
		{
			get
			{
				return this._sach_id;
			}
			set
			{
				if ((this._sach_id != value))
				{
					this.Onsach_idChanging(value);
					this.SendPropertyChanging();
					this._sach_id = value;
					this.SendPropertyChanged("sach_id");
					this.Onsach_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_sach", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string ten_sach
		{
			get
			{
				return this._ten_sach;
			}
			set
			{
				if ((this._ten_sach != value))
				{
					this.Onten_sachChanging(value);
					this.SendPropertyChanging();
					this._ten_sach = value;
					this.SendPropertyChanged("ten_sach");
					this.Onten_sachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tac_gia_id", DbType="Int")]
		public System.Nullable<int> tac_gia_id
		{
			get
			{
				return this._tac_gia_id;
			}
			set
			{
				if ((this._tac_gia_id != value))
				{
					if (this._tac_gia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontac_gia_idChanging(value);
					this.SendPropertyChanging();
					this._tac_gia_id = value;
					this.SendPropertyChanged("tac_gia_id");
					this.Ontac_gia_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nha_xuat_ban_id", DbType="Int")]
		public System.Nullable<int> nha_xuat_ban_id
		{
			get
			{
				return this._nha_xuat_ban_id;
			}
			set
			{
				if ((this._nha_xuat_ban_id != value))
				{
					if (this._nha_xuat_ban.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnha_xuat_ban_idChanging(value);
					this.SendPropertyChanging();
					this._nha_xuat_ban_id = value;
					this.SendPropertyChanged("nha_xuat_ban_id");
					this.Onnha_xuat_ban_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_tien", DbType="Decimal(10,2) NOT NULL")]
		public decimal gia_tien
		{
			get
			{
				return this._gia_tien;
			}
			set
			{
				if ((this._gia_tien != value))
				{
					this.Ongia_tienChanging(value);
					this.SendPropertyChanging();
					this._gia_tien = value;
					this.SendPropertyChanged("gia_tien");
					this.Ongia_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chu_de_id", DbType="Int")]
		public System.Nullable<int> chu_de_id
		{
			get
			{
				return this._chu_de_id;
			}
			set
			{
				if ((this._chu_de_id != value))
				{
					if (this._chu_de.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onchu_de_idChanging(value);
					this.SendPropertyChanging();
					this._chu_de_id = value;
					this.SendPropertyChanged("chu_de_id");
					this.Onchu_de_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anhSP", DbType="NVarChar(255)")]
		public string anhSP
		{
			get
			{
				return this._anhSP;
			}
			set
			{
				if ((this._anhSP != value))
				{
					this.OnanhSPChanging(value);
					this.SendPropertyChanging();
					this._anhSP = value;
					this.SendPropertyChanged("anhSP");
					this.OnanhSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayCapNhap
		{
			get
			{
				return this._NgayCapNhap;
			}
			set
			{
				if ((this._NgayCapNhap != value))
				{
					this.OnNgayCapNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhap = value;
					this.SendPropertyChanged("NgayCapNhap");
					this.OnNgayCapNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="NVarChar(MAX)")]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sach_chi_tiet_dat_hang", Storage="_chi_tiet_dat_hangs", ThisKey="sach_id", OtherKey="sach_id")]
		public EntitySet<chi_tiet_dat_hang> chi_tiet_dat_hangs
		{
			get
			{
				return this._chi_tiet_dat_hangs;
			}
			set
			{
				this._chi_tiet_dat_hangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sach_viet_sach", Storage="_viet_saches", ThisKey="sach_id", OtherKey="sach_id")]
		public EntitySet<viet_sach> viet_saches
		{
			get
			{
				return this._viet_saches;
			}
			set
			{
				this._viet_saches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nha_xuat_ban_sach", Storage="_nha_xuat_ban", ThisKey="nha_xuat_ban_id", OtherKey="nha_xuat_ban_id", IsForeignKey=true)]
		public nha_xuat_ban nha_xuat_ban
		{
			get
			{
				return this._nha_xuat_ban.Entity;
			}
			set
			{
				nha_xuat_ban previousValue = this._nha_xuat_ban.Entity;
				if (((previousValue != value) 
							|| (this._nha_xuat_ban.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nha_xuat_ban.Entity = null;
						previousValue.saches.Remove(this);
					}
					this._nha_xuat_ban.Entity = value;
					if ((value != null))
					{
						value.saches.Add(this);
						this._nha_xuat_ban_id = value.nha_xuat_ban_id;
					}
					else
					{
						this._nha_xuat_ban_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("nha_xuat_ban");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chu_de_sach", Storage="_chu_de", ThisKey="chu_de_id", OtherKey="chu_de_id", IsForeignKey=true, DeleteRule="CASCADE")]
		public chu_de chu_de
		{
			get
			{
				return this._chu_de.Entity;
			}
			set
			{
				chu_de previousValue = this._chu_de.Entity;
				if (((previousValue != value) 
							|| (this._chu_de.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chu_de.Entity = null;
						previousValue.saches.Remove(this);
					}
					this._chu_de.Entity = value;
					if ((value != null))
					{
						value.saches.Add(this);
						this._chu_de_id = value.chu_de_id;
					}
					else
					{
						this._chu_de_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("chu_de");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tac_gia_sach", Storage="_tac_gia", ThisKey="tac_gia_id", OtherKey="tac_gia_id", IsForeignKey=true)]
		public tac_gia tac_gia
		{
			get
			{
				return this._tac_gia.Entity;
			}
			set
			{
				tac_gia previousValue = this._tac_gia.Entity;
				if (((previousValue != value) 
							|| (this._tac_gia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tac_gia.Entity = null;
						previousValue.saches.Remove(this);
					}
					this._tac_gia.Entity = value;
					if ((value != null))
					{
						value.saches.Add(this);
						this._tac_gia_id = value.tac_gia_id;
					}
					else
					{
						this._tac_gia_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tac_gia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chi_tiet_dat_hangs(chi_tiet_dat_hang entity)
		{
			this.SendPropertyChanging();
			entity.sach = this;
		}
		
		private void detach_chi_tiet_dat_hangs(chi_tiet_dat_hang entity)
		{
			this.SendPropertyChanging();
			entity.sach = null;
		}
		
		private void attach_viet_saches(viet_sach entity)
		{
			this.SendPropertyChanging();
			entity.sach = this;
		}
		
		private void detach_viet_saches(viet_sach entity)
		{
			this.SendPropertyChanging();
			entity.sach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tac_gia")]
	public partial class tac_gia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tac_gia_id;
		
		private string _ten_tac_gia;
		
		private EntitySet<sach> _saches;
		
		private EntitySet<viet_sach> _viet_saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontac_gia_idChanging(int value);
    partial void Ontac_gia_idChanged();
    partial void Onten_tac_giaChanging(string value);
    partial void Onten_tac_giaChanged();
    #endregion
		
		public tac_gia()
		{
			this._saches = new EntitySet<sach>(new Action<sach>(this.attach_saches), new Action<sach>(this.detach_saches));
			this._viet_saches = new EntitySet<viet_sach>(new Action<viet_sach>(this.attach_viet_saches), new Action<viet_sach>(this.detach_viet_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tac_gia_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tac_gia_id
		{
			get
			{
				return this._tac_gia_id;
			}
			set
			{
				if ((this._tac_gia_id != value))
				{
					this.Ontac_gia_idChanging(value);
					this.SendPropertyChanging();
					this._tac_gia_id = value;
					this.SendPropertyChanged("tac_gia_id");
					this.Ontac_gia_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_tac_gia", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ten_tac_gia
		{
			get
			{
				return this._ten_tac_gia;
			}
			set
			{
				if ((this._ten_tac_gia != value))
				{
					this.Onten_tac_giaChanging(value);
					this.SendPropertyChanging();
					this._ten_tac_gia = value;
					this.SendPropertyChanged("ten_tac_gia");
					this.Onten_tac_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tac_gia_sach", Storage="_saches", ThisKey="tac_gia_id", OtherKey="tac_gia_id")]
		public EntitySet<sach> saches
		{
			get
			{
				return this._saches;
			}
			set
			{
				this._saches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tac_gia_viet_sach", Storage="_viet_saches", ThisKey="tac_gia_id", OtherKey="tac_gia_id")]
		public EntitySet<viet_sach> viet_saches
		{
			get
			{
				return this._viet_saches;
			}
			set
			{
				this._viet_saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.tac_gia = this;
		}
		
		private void detach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.tac_gia = null;
		}
		
		private void attach_viet_saches(viet_sach entity)
		{
			this.SendPropertyChanging();
			entity.tac_gia = this;
		}
		
		private void detach_viet_saches(viet_sach entity)
		{
			this.SendPropertyChanging();
			entity.tac_gia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.viet_sach")]
	public partial class viet_sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tac_gia_id;
		
		private int _sach_id;
		
		private EntityRef<sach> _sach;
		
		private EntityRef<tac_gia> _tac_gia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontac_gia_idChanging(int value);
    partial void Ontac_gia_idChanged();
    partial void Onsach_idChanging(int value);
    partial void Onsach_idChanged();
    #endregion
		
		public viet_sach()
		{
			this._sach = default(EntityRef<sach>);
			this._tac_gia = default(EntityRef<tac_gia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tac_gia_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int tac_gia_id
		{
			get
			{
				return this._tac_gia_id;
			}
			set
			{
				if ((this._tac_gia_id != value))
				{
					if (this._tac_gia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontac_gia_idChanging(value);
					this.SendPropertyChanging();
					this._tac_gia_id = value;
					this.SendPropertyChanged("tac_gia_id");
					this.Ontac_gia_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sach_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int sach_id
		{
			get
			{
				return this._sach_id;
			}
			set
			{
				if ((this._sach_id != value))
				{
					if (this._sach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsach_idChanging(value);
					this.SendPropertyChanging();
					this._sach_id = value;
					this.SendPropertyChanged("sach_id");
					this.Onsach_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sach_viet_sach", Storage="_sach", ThisKey="sach_id", OtherKey="sach_id", IsForeignKey=true)]
		public sach sach
		{
			get
			{
				return this._sach.Entity;
			}
			set
			{
				sach previousValue = this._sach.Entity;
				if (((previousValue != value) 
							|| (this._sach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sach.Entity = null;
						previousValue.viet_saches.Remove(this);
					}
					this._sach.Entity = value;
					if ((value != null))
					{
						value.viet_saches.Add(this);
						this._sach_id = value.sach_id;
					}
					else
					{
						this._sach_id = default(int);
					}
					this.SendPropertyChanged("sach");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tac_gia_viet_sach", Storage="_tac_gia", ThisKey="tac_gia_id", OtherKey="tac_gia_id", IsForeignKey=true)]
		public tac_gia tac_gia
		{
			get
			{
				return this._tac_gia.Entity;
			}
			set
			{
				tac_gia previousValue = this._tac_gia.Entity;
				if (((previousValue != value) 
							|| (this._tac_gia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tac_gia.Entity = null;
						previousValue.viet_saches.Remove(this);
					}
					this._tac_gia.Entity = value;
					if ((value != null))
					{
						value.viet_saches.Add(this);
						this._tac_gia_id = value.tac_gia_id;
					}
					else
					{
						this._tac_gia_id = default(int);
					}
					this.SendPropertyChanged("tac_gia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
